name: waste_app
description: "A new Flutter project for Final Capstone Project Telecommunication
  Engineering"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  camera: ^0.11.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.7.2+1
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.9
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/svg/
    - assets/png/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
